name: GitHub metrics

on:
  schedule: [{ cron: "5 4 * * *" }]
  push:
    branches:
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: gordonpn
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_followup: yes
          plugin_habits: yes
          plugin_habits_from: 100
          plugin_languages: yes
          plugin_lines: yes
          plugin_traffic: yes
