name: GitHub metrics

on:
  schedule: [{ cron: "5 4 * * *" }]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: gordonpn
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Toronto
          use_prebuilt_image: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request, issue
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
