name: WakaTime metrics

on:
  schedule:
    - cron: "0 10 * * *"
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
