name: WakaTime metrics

on:
  schedule: [{ cron: "5 4 * * *" }]

jobs:
  update-readme:
    name: Update WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
